language: python

python:
    - "3.5"
    - "3.6"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda config --add channels conda-forge

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numba pytest h5py matplotlib lmfit nbconvert ipykernel
    - pip install pytest-cov
    - pip install python-coveralls
    - python setup.py build
    - pip install .
    - rm -rf build/

script:
    - py.test --cov=pycorrelate -v
    - cd docs/notebooks
    - python ../../tests/nbrun.py .

after_success:
  - coveralls

sudo: false
